remote_theme: "pages-themes/midnight@v0.2.0"

title: Oliver Freyermuth
tagline: A collection of my projects
description: >-
  This personal page of Oliver Freyermuth is a collection of some of the projects he works on,
  including both creative and technical content.
show_downloads: false
google_analytics:

my_github_url: https://github.com/olifre

collections:
  knowledgebase:
    output: true
    permalink: /:collection/:title/

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude Google site verification.
defaults:
  - scope:
      path: "google*.html"
    values:
      sitemap: false

jekyll_sitemap:
  index:
    filename: sitemap-index.xml
    linked_sitemaps:
      - https://olifre.github.io/lifelines/sitemap.xml
      - https://olifre.github.io/mybooks/sitemap.xml
