theme: jekyll-theme-midnight

title: Oliver Freyermuth
description: A collection of my projects
show_downloads: false
google_analytics:

my_github_url: https://github.com/olifre

collections:
  knowledgebase:
    output: true
    permalink: /:collection/:title/

plugins:
  - jekyll-sitemap

# Exclude Google site verification.
defaults:
  - scope:
      path: "google*.html"
    values:
      sitemap: false
