theme: jekyll-theme-midnight

title: Oliver Freyermuth
tagline: A collection of my projects
description: >-
  This personal page of Oliver Freyermuth is a collection of some of the projects he works on,
  and shares some collected technical information in form of a knowledgebase.
show_downloads: false
google_analytics:

my_github_url: https://github.com/olifre

collections:
  knowledgebase:
    output: true
    permalink: /:collection/:title/

plugins:
  - jekyll-sitemap

# Exclude Google site verification.
defaults:
  - scope:
      path: "google*.html"
    values:
      sitemap: false
