baseURL = 'https://olifre.github.io/'
defaultContentLanguage = "en"
localte = "en-us"
enableEmoji = true
enableRobotsTXT = true
pygmentsStyle = "solarized-dark"
theme = "gokarna"
title = "Oliver Freyermuth"

[params]
  description = "A collection of my projects"
  footer = "Oliver Freyermuth"
  metaKeywords = ["blog", "personal"]
  socialIcons = [
    {name = "keybase", url = "https://keybase.io/olifre"},
    {name = "stackoverflow", url = "https://stackoverflow.com/users/9679188/oliver-freyermuth"},
  ]

  myGhUser = "olifre"

  accentColor = "darkgoldenrod"
  #accentColor = "#ffeb9b"
  showBackToTopButton = true
  togglePreviousAndNextButtons = true
  displayReadingTime = true

  relativeURLs = true
  customHeadHTML = """
    <link rel="stylesheet" type="text/css" href="/olifre-new.github.io/css/custom.css" />
"""

[menu]
  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Technical"
    pre = "<span data-feather='code'></span>"
    url = "technical_projects"
    weight = 2

  [[menu.main]]
    name = "Publications"
    pre = "<span data-feather='file-text'></span>"
    url = "publications"
    weight = 3

  [[menu.main]]
    name = "Creative"
    pre = "<span data-feather='book-open'></span>"
    url = "creative_projects"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 5
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/olifre"
    weight = 6
    pre = "<span data-feather='github'></span>"
    post = ""

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true

#[markup.goldmark.renderer]
#    unsafe = true
